#########################################################
# DO Community Playbooks: Wordpress on Ubuntu 20.04 LAMP
#########################################################
---
- hosts: production
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install PHP Extensions
      apt: name={{ item }} update_cache=yes state=latest
      loop: "{{ php_modules }}"
      tags: [ system ]

    # Apache Configuration
    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ wordpress ]
  
